//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rotterdam.Data.Sql.EntityFramework.Static
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataspaceProperty
    {
        public DataspaceProperty()
        {
            this.DataspaceHierarchies = new HashSet<DataspaceHierarchy>();
            this.DataspaceTypePropertyMappings = new HashSet<DataspaceTypePropertyMapping>();
        }
    
        public System.Guid DataspacePropertyId { get; set; }
        public System.Guid DataspaceId { get; set; }
        public bool IsKey { get; set; }
        public bool IsSystem { get; set; }
        public string Property { get; set; }
        public string Regex { get; set; }
        public string Flag { get; set; }
        public string SystemName { get; set; }
        public string DisplayName { get; set; }
    
        public virtual ICollection<DataspaceHierarchy> DataspaceHierarchies { get; set; }
        public virtual ICollection<DataspaceTypePropertyMapping> DataspaceTypePropertyMappings { get; set; }
    }
}
