//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rotterdam.Data.Sql.EntityFramework.Static
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataspaceReference
    {
        public System.Guid ProviderDataspaceReferenceId { get; set; }
        public System.Guid DataspaceId { get; set; }
        public System.Guid ManagedEntityId { get; set; }
    
        public virtual ManagedEntity ManagedEntity { get; set; }
    }
}
