//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rotterdam.Data.Sql.EntityFramework.Static
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataspaceHierarchy
    {
        public DataspaceHierarchy()
        {
            this.DataspaceHierarchyMappings = new HashSet<DataspaceHierarchyMapping>();
        }
    
        public System.Guid DataspaceHierarchyId { get; set; }
        public System.Guid DataspaceId { get; set; }
        public System.Guid DataspacePropertyId { get; set; }
        public string RegularExpression { get; set; }
    
        public virtual Dataspace Dataspace { get; set; }
        public virtual DataspaceProperty DataspaceProperty { get; set; }
        public virtual ICollection<DataspaceHierarchyMapping> DataspaceHierarchyMappings { get; set; }
    }
}
