//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rotterdam.Data.Sql.EntityFramework.Static
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataspaceHierarchyMapping
    {
        public System.Guid DataspaceHierarchyMappingId { get; set; }
        public System.Guid DataspaceHierarchyId { get; set; }
        public System.Guid ManagedTypeId { get; set; }
        public int Ordinal { get; set; }
    
        public virtual DataspaceHierarchy DataspaceHierarchy { get; set; }
        public virtual ManagedType ManagedType { get; set; }
    }
}
