//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rotterdam.Data.Sql.EntityFramework.Static
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataspaceTypePropertyMapping
    {
        public System.Guid DataspaceTypeMappingAttributeId { get; set; }
        public System.Guid DataspacePropertyId { get; set; }
        public System.Guid ManagedTypePropertyId { get; set; }
    
        public virtual DataspaceProperty DataspaceProperty { get; set; }
        public virtual ManagedTypeProperty ManagedTypeProperty { get; set; }
    }
}
