//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rotterdam.Data.Sql.EntityFramework.Static
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dataspace
    {
        public Dataspace()
        {
            this.DataspaceHierarchies = new HashSet<DataspaceHierarchy>();
            this.DataspaceTypeMappings = new HashSet<DataspaceTypeMapping>();
        }
    
        public System.Guid DataspaceId { get; set; }
        public System.Guid ProviderId { get; set; }
        public string Name { get; set; }
        public string Realm { get; set; }
        public string Object { get; set; }
        public bool IsEnabled { get; set; }
        public bool IsIngested { get; set; }
        public Nullable<System.DateTime> Bookmark { get; set; }
        public string Configuration { get; set; }
        public string Filter { get; set; }
        public string Cachespace { get; set; }
    
        public virtual ICollection<DataspaceHierarchy> DataspaceHierarchies { get; set; }
        public virtual ICollection<DataspaceTypeMapping> DataspaceTypeMappings { get; set; }
    }
}
