//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rotterdam.Data.Sql.EntityFramework.Static
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManagedEntity
    {
        public ManagedEntity()
        {
            this.DataspaceReferences = new HashSet<DataspaceReference>();
        }
    
        public System.Guid ManagedEntityId { get; set; }
        public System.Guid ManagedTypeId { get; set; }
        public string Name { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    
        public virtual ICollection<DataspaceReference> DataspaceReferences { get; set; }
        public virtual ManagedType ManagedType { get; set; }
        public virtual ManagedTreeEntity ManagedTreeEntity { get; set; }
    }
}
