//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rotterdam.Data.Sql.EntityFramework.Static
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManagedTree
    {
        public ManagedTree()
        {
            this.ManagedTreeEntities = new HashSet<ManagedTreeEntity>();
        }
    
        public System.Guid ManagedTreeId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ManagedTreeEntity> ManagedTreeEntities { get; set; }
    }
}
