//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rotterdam.Data.Sql.EntityFramework.Static
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManagedTypeProperty
    {
        public ManagedTypeProperty()
        {
            this.DataspaceTypePropertyMappings = new HashSet<DataspaceTypePropertyMapping>();
        }
    
        public System.Guid ManagedTypePropertyId { get; set; }
        public System.Guid ManagedTypeId { get; set; }
        public string Name { get; set; }
        public string ColumnName { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public bool IsRequired { get; set; }
        public bool IsPrimaryKey { get; set; }
        public bool IsCaseSensitive { get; set; }
        public bool IsWriteableByUser { get; set; }
        public bool IsWriteableByDataspace { get; set; }
        public int Ordinal { get; set; }
        public int MinLength { get; set; }
        public int MaxLength { get; set; }
        public Nullable<int> MinValue { get; set; }
        public Nullable<int> MaxValue { get; set; }
        public string RegEx { get; set; }
        public Nullable<System.Guid> EnumTypeId { get; set; }
        public string DefaultValue { get; set; }
    
        public virtual ICollection<DataspaceTypePropertyMapping> DataspaceTypePropertyMappings { get; set; }
        public virtual ManagedType ManagedType { get; set; }
    }
}
