//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rotterdam.Data.Sql.EntityFramework.Static
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider
    {
        public System.Guid ProviderId { get; set; }
        public string ProviderName { get; set; }
        public string AssemblyName { get; set; }
        public string AssemblyPath { get; set; }
        public bool IsEnabled { get; set; }
        public bool IsIngested { get; set; }
    }
}
