//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rotterdam.Data.Sql.EntityFramework.Static
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderEndpoint
    {
        public System.Guid ProviderEndpointId { get; set; }
        public System.Guid TypeId { get; set; }
        public string Name { get; set; }
        public bool IsEnabled { get; set; }
        public string Endpoint { get; set; }
    }
}
