//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rotterdam.Data.Sql.EntityFramework.Static
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RotterdamContext : DbContext
    {
        public RotterdamContext()
            : base("name=RotterdamContext")
        {
        }
    
    	public RotterdamContext(string nameOrConnectionString)
            : base(nameOrConnectionString)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dataspace> Dataspaces { get; set; }
        public virtual DbSet<DataspaceHierarchy> DataspaceHierarchies { get; set; }
        public virtual DbSet<DataspaceHierarchyMapping> DataspaceHierarchyMappings { get; set; }
        public virtual DbSet<DataspaceProperty> DataspaceProperties { get; set; }
        public virtual DbSet<DataspaceReference> DataspaceReferences { get; set; }
        public virtual DbSet<DataspaceTypeMapping> DataspaceTypeMappings { get; set; }
        public virtual DbSet<DataspaceTypePropertyMapping> DataspaceTypePropertyMappings { get; set; }
        public virtual DbSet<ManagedEntity> ManagedEntities { get; set; }
        public virtual DbSet<ManagedTree> ManagedTrees { get; set; }
        public virtual DbSet<ManagedTreeEntity> ManagedTreeEntities { get; set; }
        public virtual DbSet<ManagedType> ManagedTypes { get; set; }
        public virtual DbSet<ManagedTypeProperty> ManagedTypeProperties { get; set; }
        public virtual DbSet<Provider> Providers { get; set; }
        public virtual DbSet<ProviderEndpoint> ProviderEndpoints { get; set; }
    }
}
